version: '3.9'

services:
  web:
    build: .
    command: python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"