# Generated by Django 4.0.2 on 2023-06-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phon_number',
            field=models.CharField(max_length=11),
        ),
    ]
